apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3k
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://rancher.github.io/k3k
    chart: k3k
    targetRevision: 1.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: k3k-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
