cleanUpCRDs: false
configuration:
  backupStorageLocation:
  - bucket: velero-suseai
    config:
      region: homelab
      s3ForcePathStyle: "true"
      s3Url: http://192.168.90.100:3900
    credential:
      key: aws
      name: bsl-credentials
    default: true
    name: default
    provider: aws
  defaultSnapshotMoveData: true
  features: EnableCSI
credentials:
  existingSecret: bsl-credentials
  useSecret: true
deployNodeAgent: true
image:
  repository: velero/velero
  tag: v1.17.1
initContainers:
- image: velero/velero-plugin-for-aws:v1.11.0
  imagePullPolicy: IfNotPresent
  name: velero-plugin-for-aws
  volumeMounts:
  - mountPath: /target
    name: plugins
kubectl:
  image:
    repository: alpine/k8s
    tag: 1.34.1
nodeAgent:
  podVolumePath: /var/lib/kubelet/pods
  privileged: true
snapshotsEnabled: false
upgradeCRDs: false
