apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      containers:
        - name: {{ .Values.serviceName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.port }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            {{- if .Values.securityContext.dropAllCapabilities }}
            capabilities:
              drop:
                - ALL
            {{- end }}
          {{- end }}
          readinessProbe:
            {{- if eq .Values.probes.type "http" }}
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.port }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.port }}
            {{- end }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          livenessProbe:
            {{- if eq .Values.probes.type "http" }}
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.port }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.port }}
            {{- end }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
