apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rajesh-kumar-in-wildcard
  namespace: certificate-ns
spec:
  secretName: rajesh-tls-cert
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - "*.rajesh-kumar.in"
    - "rajesh-kumar.in"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
