USER-SUPPLIED VALUES:
configs:
  params:
    server.insecure: "true"
global:
  domain: argocd.rajesh-kumar.in
server:
  httproute:
    enabled: true
    hostnames:
    - argocd.rajesh-kumar.in
    parentRefs:
    - name: common-server-gateway
      namespace: common-gateway
      sectionName: https-listener
  ingress:
    enabled: false
