apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3k-virtual-a-manifests
  namespace: argocd
spec:
  project: default
  destination:
    name: k3k-virtual-a
    namespace: default
  source:
    repoURL: https://github.com/rajeshkio/pulumiInfraProxmox.git
    targetRevision: HEAD
    path: argocd/k3k-clusters/virtual-a/manifests 
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
