USER-SUPPLIED VALUES:
csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1
defaultBackupStore:
  backupstorePollInterval: 300
defaultSettings:
  backupBlockSize: "2"
  defaultDataPath: /mnt/nas-storage/longhorn
  defaultReplicaCount: "1"
  v1DataEngine: true
global:
  cattle:
    clusterId: c-wdjwc
    clusterName: ai-cluster
    rkePathPrefix: ""
    rkeWindowsPathPrefix: ""
    systemDefaultRegistry: registry.rancher.com
    systemProjectId: p-dp9jf
    url: https://rancher.rajesh-kumar.in
  systemDefaultRegistry: registry.rancher.com
image:
  defaultImage: true
longhorn:
  default_resource: true
  default_setting: true
persistence:
  defaultClassReplicaCount: 1
